name: CI

on:
  push:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run tests
        run: cargo test --verbose | tee test.log
      - name: Test summary
        if: always()
        run: |
          echo "### Test Results" >> "$GITHUB_STEP_SUMMARY"
          grep '^test ' test.log >> "$GITHUB_STEP_SUMMARY" || true
          grep '^test result:' test.log >> "$GITHUB_STEP_SUMMARY" || true
          if grep -q '^failures:' test.log; then
            echo '' >> "$GITHUB_STEP_SUMMARY"
            sed -n '/^failures:/,/^test result:/p' test.log >> "$GITHUB_STEP_SUMMARY"
          fi

