name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run tests
        run: cargo test --all-targets --verbose | tee test.log
      - name: Ensure release build
        run: cargo build --release
      - name: Test summary
        if: always()
        run: |
          echo "### Test Results" >> "$GITHUB_STEP_SUMMARY"
          awk '/^test .* \.{3}/ {printf "| `%s` | %s |\n", $2, $NF}' test.log > table.tmp
          if [ -s table.tmp ]; then
            {
              echo "| Test | Result |"
              echo "| ---- | ------ |"
              cat table.tmp
            } >> "$GITHUB_STEP_SUMMARY"
          fi
          summary=$(grep '^test result:' test.log | tail -n1)
          if [ -n "$summary" ]; then
            echo '' >> "$GITHUB_STEP_SUMMARY"
            echo "\`$summary\`" >> "$GITHUB_STEP_SUMMARY"
          fi
          if grep -q '^failures:' test.log; then
            echo '' >> "$GITHUB_STEP_SUMMARY"
            echo '<details><summary>Failures</summary>' >> "$GITHUB_STEP_SUMMARY"
            sed -n '/^failures:/,/^test result:/p' test.log >> "$GITHUB_STEP_SUMMARY"
            echo '</details>' >> "$GITHUB_STEP_SUMMARY"
          fi

